#!/bin/bash

# Update the package lists for upgrades and new package installations
sudo apt-get -y update

# Install nginx
apt-get install -y nginx

# Make sure nginx is started
service nginx start

# Configure nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create a custom homepage
echo "Hello World!" > /var/www/html/index.html

# Restart nginx to apply the changes
sudo service nginx restart
