#!/usr/bin/env bash
# installing nginx on web server

# Update the package lists for upgrades and new package installations
apt-get -y update

# Install nginx
apt-get -y install nginx

# Create a custom homepage
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Configure nginx to listen on port 80
sed -i 's/8080/80/g' /etc/nginx/sites-available/default

# Add redirection rule
echo "location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}" | sudo tee -a /etc/nginx/sites-available/default

# Restart nginx to apply the changes
service nginx restart
