#!/usr/bin/env bash
# configuring nginx
# Configure nginx to listen on port 80
sudo sed -i 's/listen [^;]*;/listen 80;/' /etc/nginx/sites-available/default

# Restart nginx to apply the changes
sudo service nginx restart
