#!/usr/bin/env bash
# Configures nginx to 80

sudo apt-get -y update

sudo apt-get -y install nginx

sudo sed -i 's/listen [^;]*;/listen 80;/' /etc/nginx/sites-available/default

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
