#!/usr/bin/env bash
apt-get -y update
apt-get -y install nginx
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
start-stop-daemon --start --background --exec /usr/sbin/nginx -- -c /etc/nginx/nginx.conf
service nginx restart
