#!/usr/bin/env bash
# This script installs and starts the nginx web server
[ $(pgrep nginx) ] || service nginx start
[ $(netstat -tulpn | grep :80) ] || (sed -i 's/listen [0-9]*;/listen 80;/' /etc/nginx/sites-available/default)
service nginx restart
