#!/usr/bin/env bash
apt-get -y update
apt-get -y install nginx
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
echo "daemon off;" | sudo tee -a /etc/nginx/nginx.conf
service nginx restart
