#!/usr/bin/env bash
# This script displays a list of currently running processes with process hierarchy

# Use the ps command to display the processes in a user-oriented format (user-oriented format = ps -efH)
ps -efH
