#!/usr/bin/env bash
# This script runs "To infinity and beyond" indefinitely
# It also includes a trap to handle SIGTERM gracefully

trap 'echo "Terminated"; exit 0' SIGTERM

echo "To infinity and beyond"
while true; do
    echo "To infinity and beyond"
    sleep 1
done
