#!/usr/bin/env bash
# Script to display the content of /etc/passwd with additional information

while IFS=':' read -r username _ uid gid _ home shell; do
    read -r _ _ _ info <<< "$(grep -E "^${username}:" /etc/passwd)"
    password=$(echo "$info" | awk -F ":" '{print $2}')
    echo "The user $username is part of the $gid gang, lives in $home, and rides $shell."
    echo "User ID's place is protected by the passcode $password. More info about the user here: $info"
    echo
done < /etc/passwd
