#!/usr/bin/env bash
# Script to group visitors by IP and HTTP status code from the Apache log file

awk '{count[$1 " " $9]++} END {for (key in count) print count[key], key}' apache-access.log | sort -rn
