#!/usr/bin/env bash
# This script runs the 'whoami' command as the specified user

# Check if script was run with an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 username"
    exit 1
fi

# Run 'whoami' command as the specified user
sudo -u "$1" whoami
