#!/usr/bin/env bash
# This script configures the container to run Nginx as 'nginx' user and listen on port 8080

# Change Nginx configuration to listen on port 8080
sed -i 's/listen 80 default_server/listen 8080 default_server/g' /etc/nginx/sites-available/default

# Change Nginx configuration to run as 'nginx' user
sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf

# Restart Nginx service
service nginx restart
